spring:
  application:
    name: b3-market-sync-api

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6381}

app:
  brapi:
    url: https://brapi.dev/api
    token: ${BRAPI_TOKEN}
    tickers:
      - "PETR4"
      - "PETR3"
      - "VALE3"
  sync:
    interval: 1800000

server:
  port: 8096

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
